[package]
name = "envoy-wasm-body-transform"
version = "0.1.0"
authors = ["Lahiru Udayanga <lahirudesilva.17@cse.mrt.ac.lk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/body_transform.rs"
#path = "src/body_filter.rs"
crate-type = ["cdylib"]

# [[bin]]
# name = "proto"
# path = "build.rs"

[dependencies]
proxy-wasm = "0.2.0"
log = "0.4"
quickxml_to_serde = "0.5.0"

[build-dependencies]
protoc-rust = "2.0"

[profile.release]
lto = true
opt-level = 'z'
strip = "debuginfo"
panic = "abort"
